# Start from the official Golang image
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Go app with static linking
RUN CGO_ENABLED=0 GOOS=linux go build -o poller ./cmd/poller

# Use a minimal image for the final build
FROM alpine:latest

WORKDIR /app

# Copy the binary from the builder
COPY --from=builder /app/poller .

# Run the binary
CMD ["./poller"]
